const API_URL = 'http://127.0.0.1:5000';

const MILLISECONDS_JS = 1;
const SECONDS_JS = MILLISECONDS_JS * 1000;
const TRANSACTIONS_INTERVAL = 10 * SECONDS_JS;

export { API_URL, TRANSACTIONS_INTERVAL };
